### ISSUE TITLE
Fails to install via pip on python 3

### ISSUE THREAD

**Issue by lsapan** [smartfile/client-python#6]
It can be installed via pip on python 2, just not python 3:

```
Lukes-iMac:~ luke$ mkvirtualenv -p /usr/local/bin/python3 testsmartfile
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5'
New python executable in testsmartfile/bin/python3.5
Also creating executable in testsmartfile/bin/python
Installing setuptools, pip, wheel...done.
(testsmartfile)Lukes-iMac:~ luke$ pip install smartfile
Collecting smartfile
  Using cached smartfile-2.1-6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/bq/489z07n11kg8gcptzrcrq8k00000gn/T/pip-build-wdtffuw6/smartfile/setup.py", line 16, in <module>
        with file(get_path('smartfile/__init__.py')) as f:
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bq/489z07n11kg8gcptzrcrq8k00000gn/T/pip-build-wdtffuw6/smartfile
```

Worth noting it still works when installing manually with `setup.py` (though that seems to be a higher version anyway).

**Comment by cabarnes** [comment]
@lsapan PyPI has been updated and this should be fixed.
